#!/bin/bash
set -e

case "$1" in
    configure)
                
        # Restart snmpd
        systemctl restart snmpd 2>/dev/null || true
        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        # Handle failure cases
        ;;
esac

#DEBHELPER#

exit 0