#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Remove our symlink/file before removal
        if [ -L /etc/snmp/snmpd.conf ] || [ -f /etc/snmp/snmpd.conf ]; then
            rm -f /etc/snmp/snmpd.conf
        fi
        ;;
esac

#DEBHELPER#

exit 0