#!/bin/bash
set -e

case "$1" in
    configure)
        # Comment out everything in snmpd.conf except the includeDir line
        if [ -f /etc/snmp/snmpd.conf ]; then
            # Create a backup
            cp /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.dpkg-old
            
            # Comment out all non-comment lines except includeDir
            sed -i '/^[[:space:]]*#/!{/^[[:space:]]*$/!{/^[[:space:]]*includeDir/!s/^/#/}}' /etc/snmp/snmpd.conf
            
            # Set proper permissions
            chmod 600 /etc/snmp/snmpd.conf
            chown root:root /etc/snmp/snmpd.conf
        fi
        
        # Restart snmpd service
        if systemctl is-active --quiet snmpd 2>/dev/null; then
            systemctl restart snmpd || true
        elif [ -x /etc/init.d/snmpd ]; then
            invoke-rc.d snmpd restart || true
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ns-agent.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ns-agent.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ns-agent.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ns-agent.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ns-agent.service' >/dev/null || true
	fi
fi
# End automatically added section
